cubac/urls.py
import django
from django.contrib import admin
from django.urls import path, include
import user.views as user_view
# import admin_dashboard.views as dashboard_view
from django.conf import settings
from django.conf.urls.static import static
from allauth.account.views import confirm_email
from django.contrib.auth import urls as auth_urls

def custom_page_not_found(request):
    return django.views.defaults.page_not_found(request, None)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('rest_auth.urls')),
    path('auth/registration/', include('rest_auth.registration.urls')),
    path('account/', include('allauth.urls')),
    path('account/registration/verify-email/<str:key>/', confirm_email, name='account_confirm_email'),
    path('authentication/', include('django.contrib.auth.urls')),
    path('login/', user_view.user_login, name="login"),
    path('register', user_view.user_registration, name="register"),
    path('logout/', user_view.user_logout, name="logout"),
    path('change_password/', user_view.change_password, name="change_password"),
    path('update_user/', user_view.update_user_info, name="update_user_info"),
    path('make_staff_account/', user_view.make_staff_account, name="make_staff_account"),
    # path('project/create_account/', user_view.create_account, name="create_account"),
    path('', include('home.urls')),
     path('__debug__/', include('debug_toolbar.urls')),

    path('call/', include('call_applications.urls')),
    path('profile/', include('profiles.urls')),
    path('application/', include('applications.urls')),

    # path('password_reset/', auth_views.password_reset, name='password_reset'),
    # path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    # path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',auth_views.password_reset_confirm, name='password_reset_confirm'),
    # path('reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    # path('task/', include('todo.urls')),
    # path('project/', include('project.urls')),
    # path('daily_report/', include('daily_report.urls')),
    # path('callback/', include('callback.urls')),
    # path('installation/', include('installation.urls')),
    # path('report/', include('report.urls')),
    # path('modification/', include('modification.urls')),
    # path('servicing/', include('servicing.urls')),
    # path('callreport/', include('callreport.urls')),
    # path('payment/', include('payment.urls')),
    # path('notifications/', include('notifications.urls', namespace='notifications')),
    # path("404/", custom_page_not_found)   
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    
    path('', views.home, name="dashboard"),
    path('home/', views.bkash, name="bkash")
]
    
    
    

applications/models.py
from tokenize import blank_re
from django.db import models
import uuid
from django.db.models import UniqueConstraint
from call_applications.models import CallForApplication 
from user.models import User

class Seat(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    room = models.CharField(max_length=100, blank=False, null=False)
    capacity = models.IntegerField(default=0, blank=False, null=False)
    call_for_application = models.ForeignKey(CallForApplication, on_delete=models.SET_NULL, null=True, blank=True)


class Transaction(models.Model):
    TYPE_CHOICE= (
        ('Manual', "Manual"),
        ("Gateway", "Gateway"),
        )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    payment_type = models.CharField(max_length=10, choices=TYPE_CHOICE,  null=False, blank=False)
    transaction_method = models.CharField(max_length=100, blank=False, null=False)
    amount = models.CharField(max_length=100, blank=False, null=False)
    transaction_from = models.CharField(max_length=100)
    transaction_id = models.CharField(max_length=100, blank=False, null=False)
    transaction_time = models.DateField(max_length=100, blank=False, null=False)
    is_approved = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)        



class Application(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    call_for_application = models.ForeignKey(CallForApplication, on_delete=models.CASCADE, null=False, blank=False)
    roll_no = models.CharField(max_length=20, blank=False, null=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)   
    data = models.JSONField(editable=False)
    is_approved = models.BooleanField(default=False)
    is_payment_done = models.BooleanField(default=False)
    gw_trx_id = models.CharField(max_length=100, null=True, blank=True)
    seat = models.ForeignKey(Seat, on_delete=models.SET_NULL, null=True, blank=True)
    is_admit_ready = models.BooleanField(default=False)
    is_seatplan_ready = models.BooleanField(default=False)
    transaction = models.ForeignKey(Transaction, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        unique_together= [['call_for_application', 'user']]
        ordering = ('roll_no',)

class PageRequest(models.Model):
    class Status(models.TextChoices):
        PENDING = "P", "Pending"
        GENERATING = "G", "Generating"
        READY = "R", "Ready"
        ERROR = "E", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.PENDING
    )
    error_msg = models.CharField(max_length=128, blank=True, null=True)
    pdf_file = models.FileField(upload_to=f"pdfs", null=True, blank=True)
    template_src = models.CharField(max_length=200, null=False, blank=False)
    base_url = models.CharField(max_length=200, null=False, blank=False)
    context = models.CharField(max_length=200, null=False, blank=False)
    season = models.CharField(max_length=200, null=False, blank=False)

templates/tables/payment_table.html
{% load static %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="payment-table">
      <thead>
        <tr>
          <th>Trx Id</th>
          <th>Method</th>
          <th>Amount</th>
          <th>From</th>
          <th>Status</th>
          <th>Date</th>
          <th>Application</th>
        
          <th>Actions</th>
        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for transaction in transactions %}
        <tr>
          <td>{{transaction.transaction_id}}</strong></td>
          <td>{{transaction.transaction_method}}</td>
          <td>{{transaction.amount}}</td>
          <td>{{transaction.transaction_from}}</td>
          <td>{% if transaction.is_approved %}<i class="bx bx-check-circle bx-sm align-middle text-success"></i>{% else %}<i class="bx bx-time bx-sm align-middle text-warning"></i>{% endif %}</td>
          <td> {{transaction.transaction_time}} </td>
          <td>

            {% if transaction.application_set.all.0.id %}
            <a href="{% url 'application_detail' transaction.application_set.all.0.id %}" class="text-primary">{{transaction.application_set.all.0.roll_no}}</a>
            {% else %}
            {{transaction.application.roll_no}}
            {% endif %}
        </td>
         

 
         
          <td>
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown">
                <i class="bx bx-dots-vertical-rounded"></i>
              </button>
             
            </div>
          </td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#payment-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#payment-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}

templates/tables/seat_plan_table.html
{% load static %}
<div class="table-responsive text-nowrap" >
    <table class="table card-table table-hover" id="payment-table">
      <thead>
        <tr>
          <th>Application</th>
          <th>Venue</th>

        </tr>
      </thead>
      <tbody class="table-border-bottom-0">
        {% for application in applications %}
        <tr>
          <td>
            <a href="{% url 'application_detail' application.id %}" class="text-primary">{{application.roll_no}}</a>
        </td>
        <td>{{application.seat.room|default:"Not Allocated"}}</strong></td>
        </tr>
       {% endfor %}

      </tbody>
    </table>
  </div>
  <link rel="stylesheet" href="{% static 'vendor/datatables/dataTables.bootstrap5.min.css' %}">


  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap5.min.js' %}"></script>


  {% if split_search == True  %}
  <script>
$(document).ready(function () {
    var table = $('#payment-table').DataTable({ 
          paging: false,
            info:false
          });

    $('#table-search').keyup(function () {
        table.search($(this).val()).draw();
    });
});
  </script>
  
{% else %}

<script>
 
  $(document).ready(function () {
    $('#payment-table').DataTable({
      paging: false,
        info:false
    });
  });
</script>

{% endif %}